name: Autobuild for Docker

on: [push, workflow_dispatch, repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm,arm64
      - name: Install builder plugin
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the image
        run: |
          docker buildx build --push \
            --tag "webssh:latest" \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .
